package de.jpx3.intave.event.packet;

import com.comphenix.protocol.PacketType;
import com.comphenix.protocol.events.ConnectionSide;

public final class PacketId {

  public static PacketType by(Client clientPacket) {
    return PacketType.findCurrent(PacketType.Protocol.PLAY, PacketType.Sender.CLIENT, clientPacket.lookupName());
  }

  public static PacketType by(Server serverPacket) {
    return PacketType.findCurrent(PacketType.Protocol.PLAY, PacketType.Sender.SERVER, serverPacket.lookupName());
  }

  private static ConnectionSide connectionSideOf(Object object) {
    return object instanceof Client ? ConnectionSide.CLIENT_SIDE : (object instanceof Server ? ConnectionSide.SERVER_SIDE : ConnectionSide.BOTH);
  }

  public enum Client {
    NONE(""),

    TELEPORT_ACCEPT("TELEPORT_ACCEPT"),
    TILE_NBT_QUERY("TILE_NBT_QUERY"),
    DIFFICULTY_CHANGE("DIFFICULTY_CHANGE"),
    CHAT_IN("CHAT"),
    CLIENT_COMMAND("CLIENT_COMMAND"),
    SETTINGS("SETTINGS"),
    TAB_COMPLETE("TAB_COMPLETE"),
    TRANSACTION("TRANSACTION"),
    ENCHANT_ITEM("ENCHANT_ITEM"),
    WINDOW_CLICK("WINDOW_CLICK"),
    CLOSE_WINDOW("CLOSE_WINDOW"),
    CUSTOM_PAYLOAD("CUSTOM_PAYLOAD"),
    B_EDIT("B_EDIT"),
    ENTITY_NBT_QUERY("ENTITY_NBT_QUERY"),
    USE_ENTITY("USE_ENTITY"),
    JIGSAW_GENERATE("JIGSAW_GENERATE"),
    KEEP_ALIVE("KEEP_ALIVE"),
    DIFFICULTY_LOCK("DIFFICULTY_LOCK"),
    POSITION("POSITION"),
    POSITION_LOOK("POSITION_LOOK"),
    LOOK("LOOK"),
    FLYING("FLYING"),
    VEHICLE_MOVE("VEHICLE_MOVE"),
    BOAT_MOVE("BOAT_MOVE"),
    PICK_ITEM("PICK_ITEM"),
    AUTO_RECIPE("AUTO_RECIPE"),
    ABILITIES("ABILITIES"),
    BLOCK_DIG("BLOCK_DIG"),
    ENTITY_ACTION("ENTITY_ACTION"),
    STEER_VEHICLE("STEER_VEHICLE"),
    RECIPE_SETTINGS("RECIPE_SETTINGS"),
    RECIPE_DISPLAYED("RECIPE_DISPLAYED"),
    ITEM_NAME("ITEM_NAME"),
    RESOURCE_PACK_STATUS("RESOURCE_PACK_STATUS"),
    ADVANCEMENTS("ADVANCEMENTS"),
    TR_SEL("TR_SEL"),
    BEACON("BEACON"),
    HELD_ITEM_SLOT("HELD_ITEM_SLOT"),
    SET_COMMAND_BLOCK("SET_COMMAND_BLOCK"),
    SET_COMMAND_MINECART("SET_COMMAND_MINECART"),
    SET_CREATIVE_SLOT("SET_CREATIVE_SLOT"),
    SET_JIGSAW("SET_JIGSAW"),
    STRUCT("STRUCT"),
    UPDATE_SIGN("UPDATE_SIGN"),
    ARM_ANIMATION("ARM_ANIMATION"),
    SPECTATE("SPECTATE"),
    USE_ITEM("USE_ITEM"),
    BLOCK_PLACE("BLOCK_PLACE"),

    ;

    private final String lookupName;

    Client(String lookupName) {
      this.lookupName = lookupName;
    }

    public String lookupName() {
      return lookupName;
    }
  }

  public enum Server {
    NONE(""),
    SPAWN_ENTITY("SPAWN_ENTITY"),
    SPAWN_ENTITY_EXPERIENCE_ORB("SPAWN_ENTITY_EXPERIENCE_ORB"),
    SPAWN_ENTITY_LIVING("SPAWN_ENTITY_LIVING"),
    SPAWN_ENTITY_PAINTING("SPAWN_ENTITY_PAINTING"),
    NAMED_ENTITY_SPAWN("NAMED_ENTITY_SPAWN"),
    ANIMATION("ANIMATION"),
    STATISTIC("STATISTIC"),
    BLOCK_BREAK("BLOCK_BREAK"),
    BLOCK_BREAK_ANIMATION("BLOCK_BREAK_ANIMATION"),
    TILE_ENTITY_DATA("TILE_ENTITY_DATA"),
    BLOCK_ACTION("BLOCK_ACTION"),
    BLOCK_CHANGE("BLOCK_CHANGE"),
    BOSS("BOSS"),
    SERVER_DIFFICULTY("SERVER_DIFFICULTY"),
    CHAT("CHAT"),
    TAB_COMPLETE("TAB_COMPLETE"),
    COMMANDS("COMMANDS"),
    TRANSACTION("TRANSACTION"),
    CLOSE_WINDOW("CLOSE_WINDOW"),
    WINDOW_ITEMS("WINDOW_ITEMS"),
    WINDOW_DATA("WINDOW_DATA"),
    SET_SLOT("SET_SLOT"),
    SET_COOLDOWN("SET_COOLDOWN"),
    CUSTOM_PAYLOAD("CUSTOM_PAYLOAD"),
    CUSTOM_SOUND_EFFECT("CUSTOM_SOUND_EFFECT"),
    KICK_DISCONNECT("KICK_DISCONNECT"),
    ENTITY_STATUS("ENTITY_STATUS"),
    EXPLOSION("EXPLOSION"),
    UNLOAD_CHUNK("UNLOAD_CHUNK"),
    GAME_STATE_CHANGE("GAME_STATE_CHANGE"),
    OPEN_WINDOW_HORSE("OPEN_WINDOW_HORSE"),
    KEEP_ALIVE("KEEP_ALIVE"),
    MAP_CHUNK("MAP_CHUNK"),
    WORLD_EVENT("WORLD_EVENT"),
    WORLD_PARTICLES("WORLD_PARTICLES"),
    LIGHT_UPDATE("LIGHT_UPDATE"),
    LOGIN("LOGIN"),
    MAP("MAP"),
    OPEN_WINDOW_MERCHANT("OPEN_WINDOW_MERCHANT"),
    REL_ENTITY_MOVE("REL_ENTITY_MOVE"),
    REL_ENTITY_MOVE_LOOK("REL_ENTITY_MOVE_LOOK"),
    ENTITY_LOOK("ENTITY_LOOK"),
    ENTITY("ENTITY"),
    VEHICLE_MOVE("VEHICLE_MOVE"),
    OPEN_BOOK("OPEN_BOOK"),
    OPEN_WINDOW("OPEN_WINDOW"),
    OPEN_SIGN_EDITOR("OPEN_SIGN_EDITOR"),
    AUTO_RECIPE("AUTO_RECIPE"),
    ABILITIES("ABILITIES"),
    COMBAT_EVENT("COMBAT_EVENT"),
    PLAYER_INFO("PLAYER_INFO"),
    LOOK_AT("LOOK_AT"),
    POSITION("POSITION"),
    RECIPES("RECIPES"),
    ENTITY_DESTROY("ENTITY_DESTROY"),
    REMOVE_ENTITY_EFFECT("REMOVE_ENTITY_EFFECT"),
    RESOURCE_PACK_SEND("RESOURCE_PACK_SEND"),
    RESPAWN("RESPAWN"),
    ENTITY_HEAD_ROTATION("ENTITY_HEAD_ROTATION"),
    MULTI_BLOCK_CHANGE("MULTI_BLOCK_CHANGE"),
    SELECT_ADVANCEMENT_TAB("SELECT_ADVANCEMENT_TAB"),
    WORLD_BORDER("WORLD_BORDER"),
    CAMERA("CAMERA"),
    HELD_ITEM_SLOT("HELD_ITEM_SLOT"),
    VIEW_CENTRE("VIEW_CENTRE"),
    VIEW_DISTANCE("VIEW_DISTANCE"),
    SPAWN_POSITION("SPAWN_POSITION"),
    SCOREBOARD_DISPLAY_OBJECTIVE("SCOREBOARD_DISPLAY_OBJECTIVE"),
    ENTITY_METADATA("ENTITY_METADATA"),
    ATTACH_ENTITY("ATTACH_ENTITY"),
    ENTITY_VELOCITY("ENTITY_VELOCITY"),
    ENTITY_EQUIPMENT("ENTITY_EQUIPMENT"),
    EXPERIENCE("EXPERIENCE"),
    UPDATE_HEALTH("UPDATE_HEALTH"),
    SCOREBOARD_OBJECTIVE("SCOREBOARD_OBJECTIVE"),
    MOUNT("MOUNT"),
    SCOREBOARD_TEAM("SCOREBOARD_TEAM"),
    SCOREBOARD_SCORE("SCOREBOARD_SCORE"),
    UPDATE_TIME("UPDATE_TIME"),
    TITLE("TITLE"),
    ENTITY_SOUND("ENTITY_SOUND"),
    NAMED_SOUND_EFFECT("NAMED_SOUND_EFFECT"),
    STOP_SOUND("STOP_SOUND"),
    PLAYER_LIST_HEADER_FOOTER("PLAYER_LIST_HEADER_FOOTER"),
    NBT_QUERY("NBT_QUERY"),
    COLLECT("COLLECT"),
    ENTITY_TELEPORT("ENTITY_TELEPORT"),
    ADVANCEMENTS("ADVANCEMENTS"),
    UPDATE_ATTRIBUTES("UPDATE_ATTRIBUTES"),
    ENTITY_EFFECT("ENTITY_EFFECT"),
    RECIPE_UPDATE("RECIPE_UPDATE"),
    TAGS("TAGS"),
    MAP_CHUNK_BULK("MAP_CHUNK_BULK"),
    SET_COMPRESSION("SET_COMPRESSION"),
    UPDATE_ENTITY_NBT("UPDATE_ENTITY_NBT"),
    CRAFT_PROGRESS_BAR("CRAFT_PROGRESS_BAR"),
    ENTITY_MOVE_LOOK("ENTITY_MOVE_LOOK"),
    STATISTICS("STATISTICS"),
    OPEN_SIGN_ENTITY("OPEN_SIGN_ENTITY"),
    UPDATE_SIGN("UPDATE_SIGN"),
    BED("BED"),
    USE_BED("USE_BED"),
    SPAWN_ENTITY_WEATHER("SPAWN_ENTITY_WEATHER"),

    ;

    private final String lookupName;

    Server(String lookupName) {
      this.lookupName = lookupName;
    }

    public String lookupName() {
      return lookupName;
    }
  }
}
